name: Setup Java Manually

on:
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # You can also use 'zulu', 'oracle', etc.
        java-version: '17'

    - name: Verify Java version
      run: java -version

  
