# File: .github/workflows/setup-java.yml
name: Setup Java Manually

on:
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 21 (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # You can also use 'zulu', 'oracle', etc.
        java-version: '21'

    - name: Verify Java version
      run: java -version

    # Add any build or deploy steps here
    # - name: Build project
    #   run: mvn clean install
