name: Setup Java Manually

on:
  workflow_dispatch:

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle' 
        java-version: '17'

    - name: Verify Java version
      run: java -version

  
