name: Parallel Matrix Example

on:
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [1.0, 2.0]
    steps:
      - name: Show OS and Version
        run: echo "Running on ${{ matrix.os }} with version ${{ matrix.version }}"

      - name: Intentionally fail for specific combinations
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.version }}" == "1.0" ]]; then
            echo "Failing this Ubuntu 1.0 job"
            exit 1
          elif [[ "${{ matrix.os }}" == "windows-latest" && "${{ matrix.version }}" == "2.0" ]]; then
            echo "Failing this Windows 2.0 job"
            exit 1
          else
            echo "Job completed successfully"
          fi
        shell: bash
