name: Needs Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the build job"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "This runs after build job"
