
name: Setup Node.js 

on:
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Verify Node.js and npm versions
      run: |
        node -v
        npm -v
