# File: .github/workflows/setup-python.yml
name: Setup Python 

on:
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Run Python script
      run: python script.py  
