name: Print Vars and Secrets

on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository secret (masked)
        run: echo "MY_SEC is ${{ secrets.MY_SEC }}"
